# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateTimeField(verbose_name=b'date recorded')),
                ('rec_temp', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rec_rh', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='wproperty',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpapp.Wstation'),
        ),
    ]
